### ISSUE TITLE
Multiple font-pickers

### ISSUE THREAD

**Issue by kiogo** [smeuli/font-picker#1]
Hello, what would be the best method to have multiple font-pickers?

**Comment by smeuli** [comment]
Unfortunately, it is currently only possible to have one font picker. I will look into it though and keep you updated.

**Comment by smeuli** [comment]
I just added the option to have multiple font pickers on the same site.

For them to work, you need to give both font pickers a `name`, and then use these names in the respective `div`s where the font pickers should be generated, and also in the class names where the fonts should be applied to.

Here's an example:

```html
<div id="font-picker-1"></div>
<div id="font-picker-2"></div>

<p class="apply-font-1">Text in font 1</p>
<p class="apply-font-2">Text in font 2</p>

<script type="text/javascript" src="./path/to/dist/index.js"></script>
<script type="text/javascript">
	const fontPicker1 = new FontPicker(
		'YOUR_API_KEY',
		'Open Sans',
		{ name: '1' }
	);
	const fontPicker2 = new FontPicker(
		'YOUR_API_KEY',
		'Roboto',
		{ name: '2' }
	);
	fontPicker1.init();
	fontPicker2.init();
</script>
```

Hope this helps :)

**Comment by kiogo** [comment]
Works great, thanks for the update!
